name: "ECR-ECS-deployment"
on:
  workflow_dispatch:

jobs:
  ECR-ECS:
    name: "Build docker image and push to ECR"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v6

      - name: "setup aws credentials"
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
