name: "ECR-ECS-deployment"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ECR-ECS:
    name: "Build docker image and push to ECR"
    runs-on: self-hosted
    steps:
      - name: "checkout"
        uses: actions/checkout@v6

      - name: "setup aws credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: us-east-1

      - name: check runner user
        run: |
          whoami
        
      - name: "login to ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "build and push image to ECR"
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: myapp
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: "setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: "select workspace"
        run: echo "TF_WORKSPACE=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate
  
      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve

      
        